services:
  - type: web
    name: safe-vault
    env: node
    plan: free
    buildCommand: npm run render-build
    startCommand: npm run start
    autoDeploy: true
    envVars:
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: VITE_API_BASE_URL
        sync: false
      - key: NODE_ENV
        value: development